#!/bin/bash
# A simple databases management system using Bash Shell
mkdir DBMS 2>> ./.error.log
clear
echo "Welcome To Data Base Managemnt System"

function mainMenu {
  echo -e "\n+---------Main Menu-------------+"
  echo "| 1. Select DB                  |"
  echo "| 2. Create DB                  |"
  echo "| 3. Rename DB                  |"
  echo "| 4. Drop DB                    |"
  echo "| 5. Show DBs                   |"
  echo "| 6. Exit                       |"
  echo "+-------------------------------+"
  echo -e "Enter Choice: \c"
  read ch
  case $ch in
    1)  ChooseDataBase ;;
    2)  createDB ;;
    3)  ChangeDBName ;;
    4)  dropDB ;;
    5)  ls ./DBMS ; mainMenu;;
    6) exit ;;
    *) echo " Wrong Choice " ; mainMenu;
  esac
}
function ChooseDataBase {
  echo -e "Enter Database Name: \c"
  read DataBaseName
  cd ./DBMS/$DataBaseName 2>>./.error.log
  if [[ $? == 0 ]]; then
    echo "Database $DataBaseName was Selected Successfuly"
    tablesMenu
  else
    echo "Database $DataBaseName not found"
    mainMenu
  fi
}
function createDB {
echo -e "Enter Database Name: \c"
read DataBaseName
mkdir ./DBMS/$DataBaseName
if [[ $? == 0 ]]
then
echo "Database Created Successfully"
else
echo "Error Creating Database $DataBaseName"
fi
mainMenu
}
function ChangeDBName {
  echo -e "Enter Current Database Name: \c"
  read DataBaseName
  echo -e "Enter New Database Name: \c"
  read newName
  mv ./DBMS/$DataBaseName ./DBMS/$newName 2>>./.error.log
  if [[ $? == 0 ]]; then
    echo "Database Renamed Successfully"
  else
    echo "Error Renaming Database"
  fi
  mainMenu
}function dropDB {
  echo -e "Enter Database Name: \c"
  read DataBaseName
  rm -r ./DBMS/$DataBaseName 2>>./.error.log
  if [[ $? == 0 ]]; then
    echo "Database Dropped Successfully"
  else
    echo "Database Not found"
  fi
  mainMenu
}
function tablesMenu {
echo -e "\n+--------Tables Menu------------+"
echo "| 1. Show Existing Tables |"
echo "| 2. Create New Table |"
echo "| 3. Add Into Table |"
echo "| 4. Select From Table |"
echo "| 5. Update Table |"
echo "| 6. Delete From Table |"
echo "| 7. Drop Table |"
echo "| 8. Back To Main Menu |"
echo "| 9. Exit |"
echo "+-------------------------------+"
echo -e "Enter Choice from 1-9: \c"
read ch
case $ch in
1) ls .; tablesMenu ;;
2) createTable ;;
3) Add;;
4) clear; selectMenu ;;
5) updateTable;;
6) deleteFromTable;;
7) dropTable;;
8) clear; cd ../.. 2>>./.error.log; mainMenu ;;
9) exit ;;
*) echo " Wrong Choice " ; tablesMenu;
esac

}
function createTable {
  echo -e "Table Name: \c"
  read tbName
  if [[ -f $tbName ]]; then
    echo "table already existed ,choose another name"
    tablesMenu
  fi
  echo -e "Number of Columns: \c"
  read colsNum
  counter=1
  sep="|"
  rSep="\n"
  pKey=""
  metaData="Field"$sep"Type"$sep"key"
  while [ $counter -le $colsNum ]
  do
    echo -e "Name of Column No.$counter: \c"
    read colName

    echo -e "Type of Column $colName: "
    select var in "int" "str"
    do
      case $var in
        int ) columnDataType="int";break;;
        str ) columnDataType="str";break;;
        * ) echo "Wrong Choice" ;;
      esac
    done
    if [[ $pKey == "" ]]; then
      echo -e "Make PrimaryKey ? "
      select var in "yes" "no"
      do
        case $var in
          yes ) pKey="PK";
          metaData+=$rSep$colName$sep$columnDataType$sep$pKey;
          break;;
          no )
          metaData+=$rSep$colName$sep$columnDataType$sep""
          break;;
          * ) echo "Wrong Choice" ;;
        esac
      done
    else
      metaData+=$rSep$colName$sep$columnDataType$sep""
    fi
    if [[ $counter == $colsNum ]]; then
      temp=$temp$colName
    else
      temp=$temp$colName$sep
    fi
    ((counter++))
  done
  touch .$tbName
  echo -e $metaData  >> .$tbName
  touch $tbName
  echo -e $temp >> $tbName
  if [[ $? == 0 ]]
  then
    echo "Table Created Successfully"
    tablesMenu
  else
    echo "Error Creating Table $tbName"
    tablesMenu
  fi
}


